services:
  firefox:
    restart: always
    image: seleniarm/standalone-firefox:104.0
    container_name: selenium_firefox
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    env_file:
      - api.env
    environment:
      - SE_DRAIN_AFTER_SESSION_COUNT=3
      - SE_START_XVFB=false
      - START_XVFB=false
      - SE_JAVA_OPTS=-Xmx256m
  capsule-farmer:
    restart: always
    image: esport-capsule-farmer:v1-arm
    container_name: capsule_farmer
    build: .
    env_file:
      - api.env
    depends_on:
      - firefox
