services:
  firefox:
    restart: always
    image: seleniarm/standalone-firefox:104.0
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    privileged: true
    environment:
      - SE_NODE_SESSION_TIMEOUT=1200
      - SE_DRAIN_AFTER_SESSION_COUNT=3
      - SE_START_XVFB=false
      - SE_SESSION_RETRY_INTERVAL=60
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 15s
      timeout: 30s
      retries: 5
  capsule-farmer:
    restart: always
    image: esport-capsule-farmer:v1-arm
    build: .
    env_file:
      - api.env
    depends_on:
      firefox:
        condition: service_healthy